### ISSUE TITLE
Minimum duration should be integer not string

### ISSUE THREAD

**Issue by Flix6x** [flexiblepower/s2-ws-json#1]
In `Duration.schema.json`:

`"minimum": "0"` should be `"minimum": 0`, because the expected type of a valid duration is an integer. Otherwise, schema validation leads to comparing an integer to a string. @wilcowijbrandi if you agree, I'll make a PR with the fix.

**Comment by wilcowijbrandi** [comment]
Thanks for pointing that out! Since the schema's are being generated it's easier for me if you just make an issue instead of a PR. :)
