### ISSUE TITLE
Add timestamp to messages

### ISSUE THREAD

**Issue by victorgarcia98** [flexiblepower/s2-ws-json#11]
While using S2 in a mocked setting, I encountered one potential improvement to the protocol: add a timestamp of the creation/sending time of the messages. 

Even though this could be added as an envelop of the S2 messages, I feel that this could have an interesting utility in some cases, for example:
- Simulation/mocking
- Troubleshooting
- Network delays

Example messages that could include this new field:
- [FRBC.ActuatorStatus](https://github.com/flexiblepower/s2-ws-json/blob/main/s2-json-schema/messages/FRBC.ActuatorStatus.schema.json)
- [FRBC.Instruction](https://github.com/flexiblepower/s2-ws-json/blob/main/s2-json-schema/messages/FRBC.Instruction.schema.json)

Please, let me know your thoughts :smile:

**Comment by lfse-slafleur** [comment]
Good that you brought this up. The difficulty here is to discern what is a concern of S2 and what is a concern of the transport protocol/application.

For instance, network delays is not a concern that the S2 protocol should fix. Rather, any messages send with transport protocols such as MQTT, AMQP, REST, websockets etc. could have a metadata envelope for testing/debugging purposes so the concern of tracing/testing/debugging is kept in-between the transport protocol and the S2 protocol. I would propose to leave this to the developers of any particular application on how to achieve this through their chosen middleware.
