### ISSUE TITLE
Missing struct for DC power measurement 

### ISSUE THREAD

**Issue by gautamrituraj** [flexiblepower/s2-ws-json#14]
Hi, 

We use FRBC for battery chargers and want to use the DC power. Unfortunately, there is no structure in the commodity for DC power measurement. 
Can we make a structure for the commodity with a name like "ELECTRIC.POWER.DC"?

Many thanks for considering my request.

Kind regards, 
Gautam

**Comment by wilcowijbrandi** [comment]
Hi Gautam,

That is a good remark, thanks for bringing it up!

Just to be sure: The PowerMeasurements are only intended for power exchanged with "the grid" (whatever that means depends a bit on the context). So if you have a battery that is connected through an inverter to the AC grid, you should use the AC power values here.

Having said that, DC grids are definitely a thing and it makes sense that S2 should support those. This Github project however is an open implementation of the EN50491-12-2 standard, and it's this standard that is lacking this support. So you're remark should be direct towards the standard, not to this project. I don't think it would be wise to deviate here from the official standard (but I would encourage you to make a fork if it's blocking you).

I'll forward your remark to the standardization working group. 

Best regards,
Wilco
