### ISSUE TITLE
Missing ActivateControlType message

### ISSUE THREAD

**Issue by tonsmets** [flexiblepower/s2-ws-json#7]
Although it is not listed in the S2 spec as a separate message, we need a mechanism to send/receive an ActivateControlType sequence. I see two options:

1. Create a new message named ActivateControlType that simply has a `message_id` and `control_type` field. This way we also adhere to the S2 standard where a `null` ControlType can be sent to deactivate any selected ControlType.
2. Extend the ControlType enum list to include a `null` entry that can be sent. We then do not need any parent message.

My preference goes to the first option since we then also have a `message_id` for this message that we can track and reply to. There is a chance we will encounter a few more of these specialty use cases so creating a set of helper messages might be needed anyway. My only concern is how we are going to communicate this or add this to the S2 spec.

![Scherm­afbeelding 2023-05-24 om 07 02 03](https://github.com/flexiblepower/s2-ws-json/assets/6669915/c423151e-9223-4115-850e-8a9083ae3255)

**Comment by wilcowijbrandi** [comment]
Hi Tom,

I think the [SelectControlType](https://github.com/flexiblepower/s2-ws-json/blob/main/s2-json-schema/messages/SelectControlType.schema.json) message already covers it. The ControlType enum already contains an item for explicitly selecting no control type.

Please close the issue if this solved your problem.

Cheers,
Wilco

**Comment by tonsmets** [comment]
Wow how did I miss that. You are right! Let's use the SelectControlType for this case!
